
사용 가능한 CPU Thread: 128
Traceback (most recent call last):
  File "/root/marl/onpolicy/train_grf.py", line 216, in <module>
    main(args = sys.argv[1:])
  File "/root/marl/onpolicy/train_grf.py", line 207, in main
    runner.run()
  File "/root/marl/onpolicy/runner/shared/football_runner.py", line 28, in run
    self.warmup()
  File "/root/marl/onpolicy/runner/shared/football_runner.py", line 153, in warmup
    self.cal_xt = xT(args = self.all_args)
  File "/root/marl/onpolicy/runner/shared/xT/cal_xT.py", line 13, in __init__
    self.df = pd.read_csv(xT_csv, header=None, skiprows=1)
  File "/root/miniconda3/envs/marl/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/root/miniconda3/envs/marl/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/root/miniconda3/envs/marl/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/root/miniconda3/envs/marl/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/root/miniconda3/envs/marl/lib/python3.9/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: './csv/compound_xt.csv'